spring:
  application:
    name: healthy-eater-api
  security:
    user:
      name: admin
      password: root

server:
  port: 8080

feign:
  client:
    edamam-api:
      url: https://api.edamam.com/api/food-database/v2/parser

jhipster:
  security:
    authentication:
      jwt:
        secret: 8ab028daa0f4b8b8e6c4ddbf32c287578ab028daa0f4b8b8e6c4ddbf32c28757
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000

app-id: ebd367b9
app-key: 8ab028daa0f4b8b8e6c4ddbf32c28757

