spring:
  application:
    name: HealthyEaterApi
  security:
    user:
      name: admin
      password: root

feign:
  client:
    edamam-api:
      url: https://api.edamam.com/api/food-database/v2/parser

app-id: ebd367b9
app-key: 8ab028daa0f4b8b8e6c4ddbf32c28757


server:
  port: 8080